name: curvenote
on:
  pull_request_target:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/publish.yml@v1
    with:
      monorepo: true
      id-pattern-regex: '^scipy-2023-(?:[a-zA-Z0-9-_]{3,15})$'
      enforce-single-folder: true
      preview-label: paper
      collection: '2023'
      submit-label: in-review
      venue: scipy
      kind: Proceeding
      path: papers/*
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
