name: publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  curvenote:
    uses: curvenote/actions/.github/workflows/publish.yml@main
    with:
      monorepo: true
      id-pattern-regex: '^scipy-2023-(?:[a-zA-Z0-9-_]{3,15})$'
      enforce-single-folder: true
      preview-label: paper
      submit-label: ready
      venue: scipy
      kind: Article
      path: papers/*
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
